services:
  lsp-backend:
    build:
      context: ./lsp-backend
      dockerfile: Dockerfile
    ports:
      - "30001:30001"
    environment:
      - PORT=30001
    networks:
      - app-network

  algogpt-frontend:
    build:
      context: ./algogpt-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
    depends_on:
      - lsp-backend
    networks:
      - app-network

  api-server:
    build:
      context: ./server 
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://algogpt_admin:password@host.docker.internal:5432/algogpt_database
      - CODE_RUNNER_URL=http://code-runner:5000
      - PYTHONPATH=/server
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app-network
    command: ["python", "-m", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]


  code-runner:
    build:
      context: ./code-runner
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    command: ["gunicorn", "-w", "4", "-b", "0.0.0.0:5000", "codeExecution:app"]
    networks:
      - app-network

networks:
  app-network:
    driver: bridge