"""Correct nullable fields

Revision ID: 27d370834c83
Revises: 44bce1454689
Create Date: 2025-03-08 17:35:18.079904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27d370834c83'
down_revision: Union[str, None] = '44bce1454689'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('problems', 'is_profiling_problem',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('problems', 'is_ai_generated',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('problems', 'is_ai_generated',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('problems', 'is_profiling_problem',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
