"""Change input_data to JSON in TestCase

Revision ID: 283cf50a1c84
Revises: 819aaeb1fdcf
Create Date: 2025-02-16 23:32:06.310871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '283cf50a1c84'
down_revision: Union[str, None] = '819aaeb1fdcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_cases', 'input_data')
    op.add_column('test_cases', sa.Column('input_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True)) # Allow NULL initially
    op.execute("UPDATE test_cases SET input_data = '{}' WHERE input_data IS NULL;".format('{}')) # Set default value for existing rows.
    op.alter_column('test_cases', 'input_data', nullable=False) # Make it NOT NULL after update

    op.drop_column('test_cases', 'expected_output')
    op.add_column('test_cases', sa.Column('expected_output', postgresql.JSONB(astext_type=sa.Text()), nullable=True)) # Allow NULL initially
    op.execute("UPDATE test_cases SET expected_output = '{}' WHERE expected_output IS NULL;".format('{}')) # Set default value for existing rows.
    op.alter_column('test_cases', 'expected_output', nullable=False) # Make it NOT NULL after update
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_cases', 'input_data')
    op.add_column('test_cases', sa.Column('input_data', sa.TEXT(), nullable=True))  # Make it nullable initially
    op.execute("UPDATE test_cases SET input_data = '' WHERE input_data IS NULL;")  # Provide a default value
    op.alter_column('test_cases', 'input_data', nullable=False)  # Then make it NOT NULL

    op.drop_column('test_cases', 'expected_output')
    op.add_column('test_cases', sa.Column('expected_output', sa.TEXT(), nullable=True))  # Make it nullable initially
    op.execute("UPDATE test_cases SET expected_output = '' WHERE expected_output IS NULL;")  # Provide a default value
    op.alter_column('test_cases', 'expected_output', nullable=False)  # Then make it NOT NULL
    # ### end Alembic commands ###
