"""Added test_case_size to test_cases table

Revision ID: 767eea0ed2e4
Revises: 991e760c77f4
Create Date: 2025-02-19 09:40:33.556745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '767eea0ed2e4'
down_revision: Union[str, None] = '991e760c77f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_cases', sa.Column('test_case_size', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_cases', 'test_case_size')
    # ### end Alembic commands ###
