"""Added order_sensitive column to test_cases table

Revision ID: 8c3076a92400
Revises: 283cf50a1c84
Create Date: 2025-02-17 22:21:46.563445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c3076a92400'
down_revision: Union[str, None] = '283cf50a1c84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_cases', sa.Column('order_sensitive', sa.BOOLEAN(), nullable=False, server_default=sa.text("TRUE")))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_cases', 'order_sensitive')
    # ### end Alembic commands ###
