"""Add user_id to submissions table

Revision ID: a09e5c350b61
Revises: 573230b483ea
Create Date: 2025-03-17 12:15:32.707200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a09e5c350b61'
down_revision: Union[str, None] = '573230b483ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_submissions_user_id'), 'submissions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_submissions_user_id'), table_name='submissions')
    op.drop_column('submissions', 'user_id')
    # ### end Alembic commands ###
