"""Add unique constraint to test_case_id in examples

Revision ID: ba36de9c3dff
Revises: dbe731a80ca6
Create Date: 2025-02-23 17:46:46.358155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba36de9c3dff'
down_revision: Union[str, None] = 'dbe731a80ca6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('examples', 'test_case_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint(None, 'examples', ['test_case_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'examples', type_='unique')
    op.alter_column('examples', 'test_case_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
