"""Insert submissions table

Revision ID: bc84aea260d8
Revises: 046ee32559f2
Create Date: 2025-02-28 23:42:33.873482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bc84aea260d8'
down_revision: Union[str, None] = '046ee32559f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('source_code', sa.Text(), nullable=False),
    sa.Column('submission_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('total_tests', sa.Integer(), nullable=True),
    sa.Column('passed_tests', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submissions_id'), 'submissions', ['id'], unique=False)
    op.create_index(op.f('ix_submissions_problem_id'), 'submissions', ['problem_id'], unique=False)
    op.create_table('submission_test_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('test_case_id', sa.Integer(), nullable=False),
    sa.Column('passed', sa.BOOLEAN(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('input_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('expected_output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('actual_output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submission_test_results_id'), 'submission_test_results', ['id'], unique=False)
    op.create_index(op.f('ix_submission_test_results_submission_id'), 'submission_test_results', ['submission_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_submission_test_results_submission_id'), table_name='submission_test_results')
    op.drop_index(op.f('ix_submission_test_results_id'), table_name='submission_test_results')
    op.drop_table('submission_test_results')
    op.drop_index(op.f('ix_submissions_problem_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_id'), table_name='submissions')
    op.drop_table('submissions')
    # ### end Alembic commands ###
