"""Change user_id to string from UUID

Revision ID: d1b24e697031
Revises: a09e5c350b61
Create Date: 2025-03-17 15:41:01.347764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1b24e697031'
down_revision: Union[str, None] = 'a09e5c350b61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('submissions', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('submissions', 'user_id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False)
    # ### end Alembic commands ###
