"""Add test_case_id to examples.

Revision ID: dbe731a80ca6
Revises: 767eea0ed2e4
Create Date: 2025-02-23 17:36:26.326299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbe731a80ca6'
down_revision: Union[str, None] = '767eea0ed2e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('examples', sa.Column('test_case_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'examples', 'test_cases', ['test_case_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'examples', type_='foreignkey')
    op.drop_column('examples', 'test_case_id')
    # ### end Alembic commands ###
