/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/problems": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Problems */
        get: operations["list_problems_problems_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/problems/{problem_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Problem */
        get: operations["get_problem_problems__problem_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/problems/{problem_id}/test-cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch Test Cases */
        get: operations["fetch_test_cases_problems__problem_id__test_cases_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/submit-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Execute Code
         * @description Fetches test cases, forwards request to code runner, and returns results.
         *     Stores submission results in the database.
         */
        post: operations["execute_code_submit_code_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analyze-complexity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyze Submission Complexity
         * @description Analyzes the time and space complexity of a successful submission,
         *     with AI enhancement to provide the final determination.
         *
         *     This endpoint:
         *     1. Verifies that the submission exists and passed all tests
         *     2. Retrieves benchmark test cases for empirical analysis
         *     3. Forwards request to code-runner service for analysis
         *     4. Enhances results with AI insights
         *     5. Returns the final complexity analysis results with only the essential information
         */
        post: operations["analyze_submission_complexity_analyze_complexity_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/run-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Code
         * @description Handles run code execution requests.
         *
         *     - Receives the user-submitted code, problem ID, and test cases.
         *     - Forwards the request to the code execution engine.
         *     - Retrieves the execution results and returns them to the client.
         *
         *     Args:
         *         request (PostRunCodeRequest): The request payload containing the code, problem ID, and test cases.
         *         db (Session): The database session dependency for querying/storing execution results.
         *
         *     Returns:
         *         JSON response with execution results.
         */
        post: operations["run_code_run_code_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chat Ai
         * @description AI Chat endpoint using LangGraph for structured chat memory with problem context.
         */
        post: operations["chat_ai_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ChatRequest */
        ChatRequest: {
            /** User Id */
            user_id: string;
            /** Problem Id */
            problem_id: number;
            /** User Message */
            user_message: string;
        };
        /** ComplexityAnalysisRequest */
        ComplexityAnalysisRequest: {
            /** Submission Id */
            submission_id: string;
        };
        /** ComplexityAnalysisResponse */
        ComplexityAnalysisResponse: {
            /** Submission Id */
            submission_id: string;
            /** Problem Id */
            problem_id: number;
            /** Time Complexity */
            time_complexity: string;
            /** Space Complexity */
            space_complexity: string;
            /** Message */
            message: string;
        };
        /** ExampleTestCaseModel */
        ExampleTestCaseModel: {
            /** Test Case Id */
            test_case_id: number;
            /** Input Data */
            input_data: Record<string, never>;
            /** Expected Output */
            expected_output: unknown;
            /** Explanation */
            explanation: string;
        };
        /** GetProblemResponse */
        GetProblemResponse: {
            /** Problem Id */
            problem_id: number;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Difficulty */
            difficulty: string;
            /** Constraints */
            constraints: string;
            /** Topics */
            topics: string[];
            /** Examples */
            examples: components["schemas"]["ExampleTestCaseModel"][];
            /** Starter Code */
            starter_code: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** PostRunCodeRequest */
        PostRunCodeRequest: {
            /** Source Code */
            source_code: string;
            /** Problem Id */
            problem_id: number;
            /** Test Cases */
            test_cases: components["schemas"]["RunCodeTestCase"][];
        };
        /** PostRunCodeResponse */
        PostRunCodeResponse: {
            /** Test Results */
            test_results: components["schemas"]["RunCodeTestCaseResult"][];
        };
        /** RunCodeTestCase */
        RunCodeTestCase: {
            /** Test Case Id */
            test_case_id: number;
            /** Input */
            input: Record<string, never>;
        };
        /** RunCodeTestCaseResult */
        RunCodeTestCaseResult: {
            /** Test Case Id */
            test_case_id: number;
            /** Input */
            input: Record<string, never>;
            /** Output */
            output: unknown;
        };
        /** SubmitCodeRequest */
        SubmitCodeRequest: {
            /** Source Code */
            source_code: string;
            /** Problem Id */
            problem_id: number;
        };
        /** SubmitCodeResponse */
        SubmitCodeResponse: {
            /** Submission Id */
            submission_id: string;
            /** Status */
            status: string;
            /** Passed Tests */
            passed_tests: number;
            /** Total Tests */
            total_tests: number;
            /** User Code */
            user_code: string;
            failing_test?: components["schemas"]["SubmitCodeTestResult"] | null;
        };
        /** SubmitCodeTestResult */
        SubmitCodeTestResult: {
            /** Test Case Id */
            test_case_id: number;
            /** Input */
            input: Record<string, never>;
            /** Output */
            output: unknown;
            /** Passed */
            passed: boolean;
            /** Expected Output */
            expected_output: unknown;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_problems_problems_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_problem_problems__problem_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                problem_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetProblemResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    fetch_test_cases_problems__problem_id__test_cases_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                problem_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    execute_code_submit_code_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitCodeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmitCodeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_submission_complexity_analyze_complexity_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ComplexityAnalysisRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComplexityAnalysisResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_code_run_code_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PostRunCodeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostRunCodeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_ai_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
