"""Add constraints column to Problem table

Revision ID: 148d996d8dac
Revises: bcb02f7bd0c7
Create Date: 2025-02-09 14:44:36.416986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '148d996d8dac'
down_revision: Union[str, None] = 'bcb02f7bd0c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problems', sa.Column('constraints', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problems', 'constraints')
    # ### end Alembic commands ###
