"""Add examples table

Revision ID: 961d85e4eff6
Revises: 148d996d8dac
Create Date: 2025-02-09 16:29:55.064444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '961d85e4eff6'
down_revision: Union[str, None] = '148d996d8dac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('examples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('input_data', sa.Text(), nullable=False),
    sa.Column('output_data', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('test_cases', 'problem_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('test_cases', 'input_data',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('test_cases', 'expected_output',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('test_cases', 'explanation')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_cases', sa.Column('explanation', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('test_cases', 'expected_output',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('test_cases', 'input_data',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('test_cases', 'problem_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_table('examples')
    # ### end Alembic commands ###
